from urllib.parse import urljoin

from src.config import settings


API_TRAILHUB_ENDPOINT = urljoin(settings.API_AUTH_URL_BASE, settings.API_TRAILHUB_ENDPOINT)
CHECK_ACCESS_ALLOW_ENDPOINT = urljoin(settings.API_AUTH_URL_BASE, settings.API_AUTH_CHECK_ACCESS_ENDPOINT)
CHECK_VALIDATE_ACCESS_TOKEN_ENDPOINT = urljoin(settings.API_AUTH_URL_BASE, settings.API_AUTH_CHECK_VALIDATE_ACCESS_TOKEN)
API_ROLES_URL_ENDPOINT = urljoin(settings.API_AUTH_URL_BASE, settings.API_AUTH_ROLES_URL_ENDPOINT)
API_AUTH_READ_USER_ENDPOINT = urljoin(settings.API_AUTH_URL_BASE, settings.API_AUTH_READ_USER_ENDPOINT)
